# Generated by Django 4.2.1 on 2023-06-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botstore', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='conversation',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='bot_response',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='user_input',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
